import React from 'react'
import { Container, Wrapper, Title, Desc, CardContainer} from './ServicesStyle'
import ServicesCards from '../Cards/ServicesCards'
import { services } from '../../data/constants'


const Projects = ({openModal,setOpenModal}) => {
  return (
    <Container id="Services">
      <Wrapper>
        <Title>Services</Title>
        <Desc>
        Here examples of images generated by ImoGen
        </Desc>
        <CardContainer>
          
           {services.map((service) => (
              <ServicesCards service={service} openModal={openModal} setOpenModal={setOpenModal}/>
            ))}
          
        </CardContainer>
      </Wrapper>
    </Container>
  )
}

export default Projects